(define (main)
	'(IDENT_T NUMLIT_T CONST_T IF_T DISPLAY_T NEWLINE_T LISTOP_T AND_T OR_T NOT_T DEFINE_T NUMBERP_T SYBMBOL_T LIST_T ZEROP_T NULLP_T CHARP_T STRINGP_T PLUS_T MINUS_T DIV_T MULT_T EQUALTO_T GT_T LT_T GTE_T LTE_T QUOTE_T)
)
